[project]
name = "bookstore-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.6",
    "django-debug-toolbar>=5.0.1",
    "django-extensions>=3.2.3",
]
